apiVersion: v1
kind: Namespace
metadata:
  name: dev-namespace
  labels:
    name: dev-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: preprod-namespace
  labels:
    name: preprod-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-namespace
  labels:
    name: prod-namespace
